In [2]:
import numpy as np

In [5]:
arr1=np.array(60)#0 d array
arr2=np.array([10,20,30,40])#1d array
arr3=np.array([[1,2,3,4,5],[4,23,78,35,11]])2d array
print(np.ndim(arr1))#to check dimensions of array
print(np.ndim(arr2))
print(np.ndim(arr3))


0
1
2


In [6]:
print(type(arr1))

<class 'numpy.ndarray'>


In [11]:
print(arr1.ndim)
print(arr3)

0
[[ 1  2  3  4  5]
 [ 4 23 78 35 11]]


In [18]:
#Broadcasting in this example lower dimension array broadcast over higherone.Every time we run this code 10 will be added to each element of arr3
b=10
print(b)
arr3=b+arr3
print(arr3)


10
[[ 51  52  53  54  55]
 [ 54  73 128  85  61]]


In [21]:
#to identify shape i.e number of rows cols in an array
print(np.shape(arr1))
print(np.shape(arr2))
print(np.shape(arr3))



()
(4,)
(2, 5)


In [28]:
#Reshape Function-- this can change the shape of existing array
newarr=arr3.reshape(10,1)
newarr2=arr3.reshape(5,2)
print(newarr)
print(newarr2)

[[ 51]
 [ 52]
 [ 53]
 [ 54]
 [ 55]
 [ 54]
 [ 73]
 [128]
 [ 85]
 [ 61]]
[[ 51  52]
 [ 53  54]
 [ 55  54]
 [ 73 128]
 [ 85  61]]


In [33]:
a1=np.array([2,3,5,7,8])
a2=np.array([4,12,4,6,9])
a=np.concatenate((a1,a2))
b=np.concatenate((a2,a1))
print(a)
print(b)

[ 2  3  5  7  8  4 12  4  6  9]
[ 4 12  4  6  9  2  3  5  7  8]


In [43]:
# String Functions
str1=np.array(['hello','world'])
print(str1)
str1.ndim
str2=np.array(["Example","ONE"])
print(str2)
result=np.char.add(str1,str2)#char.add function add each index values of string
print(result)

z=np.char.replace(str1,'hello','hi')#it replaces particular substring with new in string(array)
print(z)
#functions to convert string in upper
aa=np.char.upper(str1)
ab=np.char.lower(str2)
print(aa,ab)

['hello' 'world']
['Example' 'ONE']
['helloExample' 'worldONE']
['hi' 'world']
['HELLO' 'WORLD'] ['example' 'one']


In [45]:
#Mathematical Function
add=np.add(a1,a2)
sub=np.subtract(a1,a2)
modulus=np.mod(a1,a2)
print(add)
print(sub)
print(modulus)

[ 6 15  9 13 17]
[-2 -9  1  1 -1]
[2 3 1 1 8]
[       16    531441       625    117649 134217728]
